# Generated by Django 5.1.7 on 2025-03-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_jobseekerprofile_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='career_goal',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='preferred_industry',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='team_player',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='appreciation_at_work',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='attention_to_detail',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='challenging_tasks',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='creative_thinking',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='enjoys_communication',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='enjoys_learning',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='enjoys_problem_solving',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='entrepreneurship',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='fast_career_growth',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='interest_in_tech',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='leadership',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='long_term_job',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='teamwork',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='uncertainty_discomfort',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='wants_to_make_impact',
            field=models.IntegerField(default=3),
        ),
    ]
