# Generated by Django 5.1.7 on 2025-03-30 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_surveyresponse_career_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='appreciation_at_work',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='attention_to_detail',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='challenging_tasks',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='creative_thinking',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='enjoys_communication',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='enjoys_learning',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='enjoys_problem_solving',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='entrepreneurship',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='fast_career_growth',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='interest_in_tech',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='long_term_job',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='uncertainty_discomfort',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='wants_to_make_impact',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q10_detail_orientation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q11_career_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q12_recognition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q13_entrepreneurship',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q14_learning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q15_impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q1_teamwork',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q2_challenging_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q3_leadership',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q4_uncertainty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q5_stability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q6_technology_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q7_problem_solving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q8_creativity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='q9_communication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
