# Generated by Django 5.1.7 on 2025-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_surveyresponse_appreciation_at_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvanalysis',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='predicted_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cvanalysis',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
