# Generated by Django 5.1.7 on 2025-03-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cvanalysis_certifications_cvanalysis_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
