# Generated by Django 5.1.7 on 2025-04-07 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cvanalysis_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(help_text='Virgülle ayrılmış şekilde yazınız. Örnek: Python, SQL, Django', max_length=300)),
                ('preferred_traits', models.JSONField(default=dict, help_text='Anket sorularına karşılık beklenen puanlar. Örn: {"q1_teamwork": 4}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
