# Generated by Django 5.1.7 on 2025-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='preferred_traits',
            field=models.TextField(blank=True, help_text="Describe the personal traits or soft skills you're looking for (e.g. teamwork, creativity, attention to detail)."),
        ),
    ]
