# Generated by Django 5.1.7 on 2025-04-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_jobposting_preferred_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobposting'),
        ),
    ]
