# Generated by Django 5.1.7 on 2025-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_jobapplication_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
