# Generated by Django 5.1.7 on 2025-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_matchresult_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
