# Generated by Django 5.1.7 on 2025-05-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_jobapplication_job_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
