# Generated by Django 5.1.7 on 2025-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_jobseekerprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cv_tips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
