# Generated by Django 5.1.7 on 2025-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
