# Generated by Django 5.1.7 on 2025-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='matched_traits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
