# Generated by Django 5.1.7 on 2025-05-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_matchresult_matched_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvanalysis',
            old_name='experience',
            new_name='work_experience',
        ),
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='experience',
            new_name='work_experience',
        ),
    ]
